version: "2.1"

volumes:
  orderer0.orderer.localcoin.jp:
  orderer1.orderer.localcoin.jp:
  orderer2.orderer.localcoin.jp:
  ordererx.orderer.localcoin.jp:  
  peer0.sdl.localcoin.jp:
  peer1.sdl.localcoin.jp:
  couchdb.localcoin.jp:

networks:
  localcoin_net:
    name: localcoin_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.1.0.0/24

services:
  tlsca.localcoin.jp:
    extends:
      file: docker-base.yaml
      service: ca-base
    environment:
      - FABRIC_CA_SERVER_PORT=6054
    ports:
      - "6054:6054"
    command: sh -c 'fabric-ca-server start -b tls-admin:tls-adminpw -d'
    volumes:
      - ${LOCAL_ROOT_PATH}/fabric-ca-server/tlsca.localcoin.jp:/etc/hyperledger/fabric-ca-server
    container_name: tlsca.localcoin.jp
    networks:
      localcoin_net:
        ipv4_address: 172.1.0.10

  ca.orderer.localcoin.jp:
    extends:
      file: docker-base.yaml
      service: ca-base
    environment:
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b ca-orderer-admin:ca-orderer-adminpw -d'
    volumes:
      - ${LOCAL_ROOT_PATH}/fabric-ca-server/ca.orderer.localcoin.jp:/etc/hyperledger/fabric-ca-server
    container_name: ca.orderer.localcoin.jp
    networks:
      localcoin_net:
        ipv4_address: 172.1.0.11

  ca.sdl.localcoin.jp:
    extends:
      file: docker-base.yaml
      service: ca-base
    environment:
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start -b ca-sdl-admin:ca-sdl-adminpw -d'
    volumes:
      - ${LOCAL_ROOT_PATH}/fabric-ca-server/ca.sdl.localcoin.jp:/etc/hyperledger/fabric-ca-server
    container_name: ca.sdl.localcoin.jp
    networks:
      localcoin_net:
        ipv4_address: 172.1.0.12

  orderer0.orderer.localcoin.jp:
    extends:
      file: docker-base.yaml
      service: orderer-base
    container_name: orderer0.orderer.localcoin.jp
    environment:
      - ORDERER_GENERAL_LOCALMSPID=ordererMSP
    command: orderer
    volumes:
      - ${LOCAL_ROOT_PATH}/fabric-ca-client/ca.orderer.localcoin.jp/users/orderer0:/var/hyperledger/orderer
      - orderer0.orderer.localcoin.jp:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
    networks:
      localcoin_net:
        ipv4_address: 172.1.0.20

  orderer1.orderer.localcoin.jp:
    extends:
      file: docker-base.yaml
      service: orderer-base
    container_name: orderer1.orderer.localcoin.jp
    environment:
      - ORDERER_GENERAL_LOCALMSPID=ordererMSP
      - ORDERER_GENERAL_LISTENPORT=8050 # 必須です
    command: orderer
    volumes:
      - ${LOCAL_ROOT_PATH}/fabric-ca-client/ca.orderer.localcoin.jp/users/orderer1:/var/hyperledger/orderer
      - orderer1.orderer.localcoin.jp:/var/hyperledger/production/orderer
    ports:
      - 8050:8050
    networks:
      localcoin_net:
        ipv4_address: 172.1.0.21

  orderer2.orderer.localcoin.jp:
    extends:
      file: docker-base.yaml
      service: orderer-base
    container_name: orderer2.orderer.localcoin.jp
    environment:
      - ORDERER_GENERAL_LOCALMSPID=ordererMSP
      - ORDERER_GENERAL_LISTENPORT=9050 # 必須です
    command: orderer
    volumes:
      - ${LOCAL_ROOT_PATH}/fabric-ca-client/ca.orderer.localcoin.jp/users/orderer2:/var/hyperledger/orderer
      - orderer2.orderer.localcoin.jp:/var/hyperledger/production/orderer
    ports:
      - 9050:9050
    networks:
      localcoin_net:
        ipv4_address: 172.1.0.22


  ordererx.orderer.localcoin.jp:
    extends:
      file: docker-base.yaml
      service: orderer-base
    container_name: orderer3.orderer.localcoin.jp
    environment:
      - ORDERER_GENERAL_LOCALMSPID=ordererMSP
      - ORDERER_GENERAL_LISTENPORT=10050 # 必須です
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:10053
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:10443
    command: orderer
    volumes:
      - ${LOCAL_ROOT_PATH}/fabric-ca-client/ca.orderer.localcoin.jp/users/ordererx:/var/hyperledger/orderer
      - ordererx.orderer.localcoin.jp:/var/hyperledger/production/orderer
    ports:
      - 10050:10050
      - 10053:10053
      - 10443:10443
    networks:
      localcoin_net:
        ipv4_address: 172.1.0.23

  peer0.sdl.localcoin.jp:
    extends:
      file: docker-base.yaml
      service: peer-base
    container_name: peer0.sdl.localcoin.jp
    environment:
      # Peer specific variabes
      - CORE_PEER_ID=peer0.sdl.localcoin.jp
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_ADDRESS=peer0.sdl.localcoin.jp:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.sdl.localcoin.jp:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.sdl.localcoin.jp:7051
      - CORE_PEER_GOSSIP_ENDPOINT=peer0.sdl.localcoin.jp:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.sdl.localcoin.jp:7051
      - CORE_PEER_LOCALMSPID=sdlMSP
    volumes:
      - ${LOCAL_ROOT_PATH}/fabric-ca-client/ca.sdl.localcoin.jp/users/peer0-sdl:/var/hyperledger/peer
      - peer0.sdl.localcoin.jp:/var/hyperledger/production
    command: peer node start
    ports:
      - 7051:7051
      - 7052:7052
    networks:
      localcoin_net:
        ipv4_address: 172.1.0.30

  peer1.sdl.localcoin.jp:
    container_name: peer1.sdl.localcoin.jp
    extends:
      file: docker-base.yaml
      service: peer-base
    environment:
      # Peer specific variabes
      - CORE_PEER_ID=peer1.sdl.localcoin.jp
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_ADDRESS=peer1.sdl.localcoin.jp:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.sdl.localcoin.jp:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.sdl.localcoin.jp:8051
      - CORE_PEER_GOSSIP_ENDPOINT=peer1.sdl.localcoin.jp:8051      
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.sdl.localcoin.jp:8051
      - CORE_PEER_LOCALMSPID=sdlMSP
    volumes:
      - ${LOCAL_ROOT_PATH}/fabric-ca-client/ca.sdl.localcoin.jp/users/peer1-sdl:/var/hyperledger/peer
      - peer1.sdl.localcoin.jp:/var/hyperledger/production
    command: peer node start
    ports:
      - 8051:8051
      - 8052:8052
    networks:
      localcoin_net:
        ipv4_address: 172.1.0.31

  couchdb.localcoin.jp:
    restart: always
    image: couchdb:3.1
    container_name: couchdb.localcoin.jp
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    volumes:
      - couchdb.localcoin.jp:/opt/couchdb/data
    ports:
      - 5984:5984
    networks:
      localcoin_net:
        ipv4_address: 172.1.0.100

  files.localcoin.jp:
    image: halverneus/static-file-server:latest
    restart: always
    ports:
      - "8888:8080"
    volumes:
      - ${LOCAL_ROOT_PATH}/fabric-ca-client:/web
    container_name: files.localcoin.jp
    networks:
      localcoin_net:
        ipv4_address: 172.1.0.101
