version: "2.1"

# 127.0.4.1       orderer.localcoin.jp
# 127.0.4.2       orderer1.localcoin.jp
# 127.0.4.3       orderer2.localcoin.jp
# 127.0.1.1       ca.orderer.localcoin.jp
# 127.0.1.2       ca.sdl.localcoin.jp
# 127.0.3.1       peer0.sdl.localcoin.jp
# 127.0.3.2       peer1.sdl.localcoin.jp
# 127.0.10.3      couchdb0.sdl.localcoin.jp
# 127.0.0.3       tlsca.localcoin.jp

volumes:
  orderer0.orderer.localcoin.jp:  
  orderer1.orderer.localcoin.jp:
  orderer2.localcoin.jp:
  peer0.sdl.localcoin.jp:
  peer1.sdl.localcoin.jp:

networks:
  localcoin_net:
    name: localcoin_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.1.0.0/24

services:
  tlsca.localcoin.jp:
    extends:
      file: docker-base.yaml
      service: ca-base
    environment:
      - FABRIC_CA_SERVER_PORT=6054
    ports:
      - "6054:6054"
    command: sh -c 'fabric-ca-server start -b tls-admin:tls-adminpw -d'
    volumes:
      - ./fabric-ca-server/tlsca.localcoin.jp:/etc/hyperledger/fabric-ca-server
    container_name: tlsca.localcoin.jp
    networks:
      localcoin_net:
        ipv4_address: 172.1.0.10

  ca.orderer.localcoin.jp:
    extends:
      file: docker-base.yaml
      service: ca-base
    environment:
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b ca-orderer-admin:ca-orderer-adminpw -d'
    volumes:
      - ./fabric-ca-server/ca.orderer.localcoin.jp:/etc/hyperledger/fabric-ca-server
    container_name: ca.orderer.localcoin.jp
    networks:
      localcoin_net:
        ipv4_address: 172.1.0.11

  ca.sdl.localcoin.jp:
    extends:
      file: docker-base.yaml
      service: ca-base
    environment:
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start -b ca-sdl-admin:ca-sdl-adminpw -d'
    volumes:
      - ./fabric-ca-server/ca.sdl.localcoin.jp:/etc/hyperledger/fabric-ca-server
    container_name: ca.sdl.localcoin.jp
    networks:
      localcoin_net:
        ipv4_address: 172.1.0.12

  orderer0.orderer.localcoin.jp:
    extends:
      file: docker-base.yaml
      service: orderer-base
    container_name: orderer0.orderer.localcoin.jp
    environment:
      - ORDERER_GENERAL_LOCALMSPID=ordererMSP
    command: orderer
    volumes:
      - ./fabric-ca-client/ca.orderer.localcoin.jp/users/orderer0:/var/hyperledger/orderer
      - orderer0.orderer.localcoin.jp:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
    networks:
      localcoin_net:
        ipv4_address: 172.1.0.20

  orderer1.orderer.localcoin.jp:
    extends:
      file: docker-base.yaml
      service: orderer-base
    container_name: orderer1.orderer.localcoin.jp
    environment:
      - ORDERER_GENERAL_LOCALMSPID=ordererMSP
    command: orderer
    volumes:
      - ./fabric-ca-client/ca.orderer.localcoin.jp/users/orderer1:/var/hyperledger/orderer
      - orderer1.orderer.localcoin.jp:/var/hyperledger/production/orderer
    ports:
      - 8050:7050
    networks:
      localcoin_net:
        ipv4_address: 172.1.0.21


  peer0.sdl.localcoin.jp:
    extends:
      file: docker-base.yaml
      service: peer-base  
    container_name: peer0.sdl.localcoin.jp
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=localcoin_net
      # Peer specific variabes
      - CORE_PEER_ID=peer0.sdl.localcoin.jp
      - CORE_PEER_ADDRESS=peer0.sdl.localcoin.jp:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.sdl.localcoin.jp:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.sdl.localcoin.jp:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.sdl.localcoin.jp:7051
      - CORE_PEER_LOCALMSPID=sdlMSP
    volumes:
      - ./fabric-ca-client/ca.sdl.localcoin.jp/users/peer0-sdl:/var/hyperledger/peer
      - peer0.sdl.localcoin.jp:/var/hyperledger/production
    command: peer node start
    ports:
      - 7051:7051
      - 7052:7052
    networks:
      localcoin_net:
        ipv4_address: 172.1.0.30
    depends_on:
      - couchdb.localcoin.jp

  peer1.sdl.localcoin.jp:
    container_name: peer1.sdl.localcoin.jp
    extends:
      file: docker-base.yaml
      service: peer-base
    environment:
      #Generic peer variables
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=localcoin_net
      # Peer specific variabes
      - CORE_PEER_ID=peer1.sdl.localcoin.jp
      - CORE_PEER_ADDRESS=peer1.sdl.localcoin.jp:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.sdl.localcoin.jp:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.sdl.localcoin.jp:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.sdl.localcoin.jp:8051
      - CORE_PEER_LOCALMSPID=sdlMSP
    volumes:
      - ./fabric-ca-client/ca.sdl.localcoin.jp/users/peer1-sdl:/var/hyperledger/peer
      - peer1.sdl.localcoin.jp:/var/hyperledger/production
    command: peer node start
    ports:
      - 8051:7051
      - 8052:7052
    networks:
      localcoin_net:
        ipv4_address: 172.1.0.31
    depends_on:
      - couchdb.localcoin.jp

  couchdb.localcoin.jp:
    restart: always
    image: couchdb:3.1
    container_name: couchdb.localcoin.jp
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 5984:5984
    networks:
      - localcoin_net